// src/themeSetting/defaultFieldOmniColors.js
// Complete default color palette dataset extracted from FieldOmni TColors

const defaultFieldOmniColors = [
  // 1. FieldOmni Brand Colors
  { color_key: 'secondary', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'brand', description: 'Secondary brand teal' },
  { color_key: 'primary_shade50', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'brand_shades', description: 'Primary brand shade 50' },
  { color_key: 'primary_shade100', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'brand_shades', description: 'Primary brand shade 100' },
  { color_key: 'primary_shade200', color_hex: '#A9EFE6', color_value_hex_int: '0xFFA9EFE6', category: 'brand_shades', description: 'Primary brand shade 200' },
  { color_key: 'primary_shade300', color_hex: '#6DE2D5', color_value_hex_int: '0xFF6DE2D5', category: 'brand_shades', description: 'Primary brand shade 300' },
  { color_key: 'primary_shade400', color_hex: '#2AD3C3', color_value_hex_int: '0xFF2AD3C3', category: 'brand_shades', description: 'Primary brand shade 400' },
  { color_key: 'primary_shade500', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'brand_shades', description: 'Primary brand shade 500 (Brand Teal)' },
  { color_key: 'primary_shade600', color_hex: '#00AA9A', color_value_hex_int: '0xFF00AA9A', category: 'brand_shades', description: 'Primary brand shade 600' },
  { color_key: 'primary_shade700', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'brand_shades', description: 'Primary brand shade 700' },
  { color_key: 'primary_shade800', color_hex: '#006E64', color_value_hex_int: '0xFF006E64', category: 'brand_shades', description: 'Primary brand shade 800' },
  { color_key: 'primary_shade900', color_hex: '#005047', color_value_hex_int: '0xFF005047', category: 'brand_shades', description: 'Primary brand shade 900' },

  { color_key: 'primary_shadow_light', color_hex: '#00C8B64D', color_value_hex_int: '0x4D00C8B6', category: 'brand', description: 'Brand light shadow' },
  { color_key: 'primary_shadow_dark', color_hex: '#00C8B680', color_value_hex_int: '0x8000C8B6', category: 'brand', description: 'Brand dark shadow' },

  { color_key: 'primary', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'brand', description: 'Primary deep navy' },
  { color_key: 'accent', color_hex: '#A9EFE6', color_value_hex_int: '0xFFA9EFE6', category: 'brand', description: 'Accent soft cyan' },

  // 2. Text Colors
  { color_key: 'textPrimary', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'text', description: 'Primary text color' },
  { color_key: 'textSecondary', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'text', description: 'Secondary text color' },
  { color_key: 'textWhite', color_hex: '#FFFFFF', color_value_hex_int: '0xFFFFFFFF', category: 'text', description: 'White text color' },

  // 3. Background Colors
  { color_key: 'light', color_hex: '#F6FBFB', color_value_hex_int: '0xFFF6FBFB', category: 'background', description: 'Light surface background' },
  { color_key: 'dark', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'background', description: 'Dark navy background' },
  { color_key: 'primaryBackground', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'background', description: 'Primary app background' },
  { color_key: 'lightContainer', color_hex: '#F6FBFB', color_value_hex_int: '0xFFF6FBFB', category: 'background', description: 'Light container background' },

  // 4. Button Colors
  { color_key: 'buttonPrimary', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'button', description: 'Primary action button' },
  { color_key: 'buttonSecondary', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'button', description: 'Secondary button' },
  { color_key: 'buttonDisabled', color_hex: '#C5DADF', color_value_hex_int: '0xFFC5DADF', category: 'button', description: 'Disabled button state' },

  // 5. Border Colors
  { color_key: 'borderPrimary', color_hex: '#C5DADF', color_value_hex_int: '0xFFC5DADF', category: 'border', description: 'Primary border' },
  { color_key: 'borderSecondary', color_hex: '#E4EFF1', color_value_hex_int: '0xFFE4EFF1', category: 'border', description: 'Secondary soft border' },

  // 6. Error and Validation Colors
  { color_key: 'error', color_hex: '#D32F2F', color_value_hex_int: '0xFFD32F2F', category: 'status', description: 'Error / alert' },
  { color_key: 'success', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'status', description: 'Success state' },
  { color_key: 'warning', color_hex: '#F57C00', color_value_hex_int: '0xFFF57C00', category: 'status', description: 'Warning state' },
  { color_key: 'info', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'status', description: 'Info state' },

  // 7. Neutral Shades
  { color_key: 'black', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'neutral', description: 'Deep slate / brand black' },
  { color_key: 'darkerGrey', color_hex: '#2C586A', color_value_hex_int: '0xFF2C586A', category: 'neutral', description: 'Darker grey' },
  { color_key: 'darkGrey', color_hex: '#7896A1', color_value_hex_int: '0xFF7896A1', category: 'neutral', description: 'Dark grey' },
  { color_key: 'grey', color_hex: '#C5DADF', color_value_hex_int: '0xFFC5DADF', category: 'neutral', description: 'Neutral grey' },
  { color_key: 'softGrey', color_hex: '#F0F7F7', color_value_hex_int: '0xFFF0F7F7', category: 'neutral', description: 'Soft grey background' },
  { color_key: 'lightGrey', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'neutral', description: 'Light grey surface' },
  { color_key: 'white', color_hex: '#FFFFFF', color_value_hex_int: '0xFFFFFFFF', category: 'neutral', description: 'Pure white' },

  // 8. Card & Surface Colors
  { color_key: 'cardBackground', color_hex: '#FFFFFF', color_value_hex_int: '0xFFFFFFFF', category: 'card', description: 'Card background' },
  { color_key: 'cardBorder', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'card', description: 'Card border' },
  { color_key: 'cardPink', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'card', description: 'Soft card tint' },
  { color_key: 'cardPinkLight', color_hex: '#F8FEFD', color_value_hex_int: '0xFFF8FEFD', category: 'card', description: 'Light soft card tint' },

  // 9. Status Backgrounds
  { color_key: 'successBg', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'status_bg', description: 'Success background badge' },
  { color_key: 'warningBg', color_hex: '#FFF3E0', color_value_hex_int: '0xFFFFF3E0', category: 'status_bg', description: 'Warning background badge' },
  { color_key: 'errorBg', color_hex: '#FFEBEE', color_value_hex_int: '0xFFFFEBEE', category: 'status_bg', description: 'Error background badge' },

  // 10. Travel, Allowance & Icons
  { color_key: 'travelBg', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'travel', description: 'Travel badge background' },
  { color_key: 'allowanceBg', color_hex: '#E4F7F5', color_value_hex_int: '0xFFE4F7F5', category: 'travel', description: 'Allowance badge background' },
  { color_key: 'iconBg', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'icons', description: 'Icon container background' },
  { color_key: 'amountText', color_hex: '#006E64', color_value_hex_int: '0xFF006E64', category: 'text', description: 'Amount highlight text' },

  // 11. Flutter Material Greys
  { color_key: 'materialGrey', color_hex: '#7896A1', color_value_hex_int: '0xFF7896A1', category: 'material_grey', description: 'Material grey base' },
  { color_key: 'materialGrey50', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'material_grey', description: 'Material grey 50' },
  { color_key: 'materialGrey100', color_hex: '#F0F7F7', color_value_hex_int: '0xFFF0F7F7', category: 'material_grey', description: 'Material grey 100' },
  { color_key: 'materialGrey200', color_hex: '#E4EFF1', color_value_hex_int: '0xFFE4EFF1', category: 'material_grey', description: 'Material grey 200' },
  { color_key: 'materialGrey300', color_hex: '#C5DADF', color_value_hex_int: '0xFFC5DADF', category: 'material_grey', description: 'Material grey 300' },
  { color_key: 'materialGrey400', color_hex: '#A1BBC3', color_value_hex_int: '0xFFA1BBC3', category: 'material_grey', description: 'Material grey 400' },
  { color_key: 'materialGrey500', color_hex: '#7896A1', color_value_hex_int: '0xFF7896A1', category: 'material_grey', description: 'Material grey 500' },
  { color_key: 'materialGrey600', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'material_grey', description: 'Material grey 600' },
  { color_key: 'materialGrey700', color_hex: '#2C586A', color_value_hex_int: '0xFF2C586A', category: 'material_grey', description: 'Material grey 700' },
  { color_key: 'materialGrey800', color_hex: '#16465D', color_value_hex_int: '0xFF16465D', category: 'material_grey', description: 'Material grey 800' },
  { color_key: 'materialGrey900', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'material_grey', description: 'Material grey 900' },

  // 12. Material Red Shades
  { color_key: 'materialRed', color_hex: '#D32F2F', color_value_hex_int: '0xFFD32F2F', category: 'material_red', description: 'Material red' },
  { color_key: 'materialRedAccent', color_hex: '#FF5252', color_value_hex_int: '0xFFFF5252', category: 'material_red', description: 'Material red accent' },
  { color_key: 'materialRed50', color_hex: '#FFEBEE', color_value_hex_int: '0xFFFFEBEE', category: 'material_red', description: 'Material red 50' },
  { color_key: 'materialRed100', color_hex: '#FFCDD2', color_value_hex_int: '0xFFFFCDD2', category: 'material_red', description: 'Material red 100' },
  { color_key: 'materialRed200', color_hex: '#EF9A9A', color_value_hex_int: '0xFFEF9A9A', category: 'material_red', description: 'Material red 200' },
  { color_key: 'materialRed300', color_hex: '#E57373', color_value_hex_int: '0xFFE57373', category: 'material_red', description: 'Material red 300' },
  { color_key: 'materialRed400', color_hex: '#EF5350', color_value_hex_int: '0xFFEF5350', category: 'material_red', description: 'Material red 400' },
  { color_key: 'materialRed500', color_hex: '#F44336', color_value_hex_int: '0xFFF44336', category: 'material_red', description: 'Material red 500' },
  { color_key: 'materialRed600', color_hex: '#E53935', color_value_hex_int: '0xFFE53935', category: 'material_red', description: 'Material red 600' },
  { color_key: 'materialRed700', color_hex: '#D32F2F', color_value_hex_int: '0xFFD32F2F', category: 'material_red', description: 'Material red 700' },
  { color_key: 'materialRed800', color_hex: '#C62828', color_value_hex_int: '0xFFC62828', category: 'material_red', description: 'Material red 800' },
  { color_key: 'materialRed900', color_hex: '#B71C1C', color_value_hex_int: '0xFFB71C1C', category: 'material_red', description: 'Material red 900' },

  // 13. Material Green Shades
  { color_key: 'materialGreen', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'material_green', description: 'Material green' },
  { color_key: 'materialGreenAccent', color_hex: '#6DE2D5', color_value_hex_int: '0xFF6DE2D5', category: 'material_green', description: 'Material green accent' },
  { color_key: 'materialGreen50', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'material_green', description: 'Material green 50' },
  { color_key: 'materialGreen100', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'material_green', description: 'Material green 100' },
  { color_key: 'materialGreen200', color_hex: '#A9EFE6', color_value_hex_int: '0xFFA9EFE6', category: 'material_green', description: 'Material green 200' },
  { color_key: 'materialGreen300', color_hex: '#6DE2D5', color_value_hex_int: '0xFF6DE2D5', category: 'material_green', description: 'Material green 300' },
  { color_key: 'materialGreen400', color_hex: '#2AD3C3', color_value_hex_int: '0xFF2AD3C3', category: 'material_green', description: 'Material green 400' },
  { color_key: 'materialGreen500', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'material_green', description: 'Material green 500' },
  { color_key: 'materialGreen600', color_hex: '#00AA9A', color_value_hex_int: '0xFF00AA9A', category: 'material_green', description: 'Material green 600' },
  { color_key: 'materialGreen700', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'material_green', description: 'Material green 700' },
  { color_key: 'materialGreen800', color_hex: '#006E64', color_value_hex_int: '0xFF006E64', category: 'material_green', description: 'Material green 800' },
  { color_key: 'materialGreen900', color_hex: '#005047', color_value_hex_int: '0xFF005047', category: 'material_green', description: 'Material green 900' },

  // 14. Material Blue Shades
  { color_key: 'materialBlue', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'material_blue', description: 'Material blue' },
  { color_key: 'materialBlueAccent', color_hex: '#176277', color_value_hex_int: '0xFF176277', category: 'material_blue', description: 'Material blue accent' },
  { color_key: 'materialBlueGrey', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'material_blue', description: 'Material blue grey' },
  { color_key: 'materialBlue50', color_hex: '#F4FAFA', color_value_hex_int: '0xFFF4FAFA', category: 'material_blue', description: 'Material blue 50' },
  { color_key: 'materialBlue100', color_hex: '#E4EFF1', color_value_hex_int: '0xFFE4EFF1', category: 'material_blue', description: 'Material blue 100' },
  { color_key: 'materialBlue200', color_hex: '#C5DADF', color_value_hex_int: '0xFFC5DADF', category: 'material_blue', description: 'Material blue 200' },
  { color_key: 'materialBlue300', color_hex: '#A1BBC3', color_value_hex_int: '0xFFA1BBC3', category: 'material_blue', description: 'Material blue 300' },
  { color_key: 'materialBlue400', color_hex: '#7896A1', color_value_hex_int: '0xFF7896A1', category: 'material_blue', description: 'Material blue 400' },
  { color_key: 'materialBlue500', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'material_blue', description: 'Material blue 500' },
  { color_key: 'materialBlue600', color_hex: '#2C586A', color_value_hex_int: '0xFF2C586A', category: 'material_blue', description: 'Material blue 600' },
  { color_key: 'materialBlue700', color_hex: '#16465D', color_value_hex_int: '0xFF16465D', category: 'material_blue', description: 'Material blue 700' },
  { color_key: 'materialBlue800', color_hex: '#0A435C', color_value_hex_int: '0xFF0A435C', category: 'material_blue', description: 'Material blue 800' },
  { color_key: 'materialBlue900', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'material_blue', description: 'Material blue 900' },

  // 15. Material Orange & Amber Shades
  { color_key: 'materialOrange', color_hex: '#00AA9A', color_value_hex_int: '0xFF00AA9A', category: 'material_orange', description: 'Material orange' },
  { color_key: 'materialOrangeAccent', color_hex: '#2AD3C3', color_value_hex_int: '0xFF2AD3C3', category: 'material_orange', description: 'Material orange accent' },
  { color_key: 'materialOrange50', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'material_orange', description: 'Material orange 50' },
  { color_key: 'materialOrange100', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'material_orange', description: 'Material orange 100' },
  { color_key: 'materialOrange200', color_hex: '#A9EFE6', color_value_hex_int: '0xFFA9EFE6', category: 'material_orange', description: 'Material orange 200' },
  { color_key: 'materialOrange300', color_hex: '#6DE2D5', color_value_hex_int: '0xFF6DE2D5', category: 'material_orange', description: 'Material orange 300' },
  { color_key: 'materialOrange400', color_hex: '#2AD3C3', color_value_hex_int: '0xFF2AD3C3', category: 'material_orange', description: 'Material orange 400' },
  { color_key: 'materialOrange500', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'material_orange', description: 'Material orange 500' },
  { color_key: 'materialOrange600', color_hex: '#00AA9A', color_value_hex_int: '0xFF00AA9A', category: 'material_orange', description: 'Material orange 600' },
  { color_key: 'materialOrange700', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'material_orange', description: 'Material orange 700' },
  { color_key: 'materialOrange800', color_hex: '#006E64', color_value_hex_int: '0xFF006E64', category: 'material_orange', description: 'Material orange 800' },
  { color_key: 'materialOrange900', color_hex: '#005047', color_value_hex_int: '0xFF005047', category: 'material_orange', description: 'Material orange 900' },

  { color_key: 'materialAmber', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'material_amber', description: 'Material amber' },
  { color_key: 'materialAmber50', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'material_amber', description: 'Material amber 50' },
  { color_key: 'materialAmber100', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'material_amber', description: 'Material amber 100' },
  { color_key: 'materialAmber200', color_hex: '#A9EFE6', color_value_hex_int: '0xFFA9EFE6', category: 'material_amber', description: 'Material amber 200' },
  { color_key: 'materialAmber300', color_hex: '#6DE2D5', color_value_hex_int: '0xFF6DE2D5', category: 'material_amber', description: 'Material amber 300' },
  { color_key: 'materialAmber400', color_hex: '#2AD3C3', color_value_hex_int: '0xFF2AD3C3', category: 'material_amber', description: 'Material amber 400' },
  { color_key: 'materialAmber500', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'material_amber', description: 'Material amber 500' },
  { color_key: 'materialAmber600', color_hex: '#00AA9A', color_value_hex_int: '0xFF00AA9A', category: 'material_amber', description: 'Material amber 600' },
  { color_key: 'materialAmber700', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'material_amber', description: 'Material amber 700' },
  { color_key: 'materialAmber800', color_hex: '#006E64', color_value_hex_int: '0xFF006E64', category: 'material_amber', description: 'Material amber 800' },
  { color_key: 'materialAmber900', color_hex: '#005047', color_value_hex_int: '0xFF005047', category: 'material_amber', description: 'Material amber 900' },

  // 16. Other Material Categories
  { color_key: 'materialDeepOrange', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'material_palette', description: 'Material deep orange' },
  { color_key: 'materialDeepPurple', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'material_palette', description: 'Material deep purple' },
  { color_key: 'materialDeepPurpleAccent', color_hex: '#176277', color_value_hex_int: '0xFF176277', category: 'material_palette', description: 'Material deep purple accent' },
  { color_key: 'materialPurple', color_hex: '#2C586A', color_value_hex_int: '0xFF2C586A', category: 'material_palette', description: 'Material purple' },
  { color_key: 'materialPurpleAccent', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'material_palette', description: 'Material purple accent' },
  { color_key: 'materialPink', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'material_palette', description: 'Material pink' },
  { color_key: 'materialIndigo', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'material_palette', description: 'Material indigo' },
  { color_key: 'materialTeal', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'material_palette', description: 'Material teal' },
  { color_key: 'materialCyan', color_hex: '#2AD3C3', color_value_hex_int: '0xFF2AD3C3', category: 'material_palette', description: 'Material cyan' },
  { color_key: 'materialBrown', color_hex: '#2C586A', color_value_hex_int: '0xFF2C586A', category: 'material_palette', description: 'Material brown' },
  { color_key: 'materialYellow', color_hex: '#A9EFE6', color_value_hex_int: '0xFFA9EFE6', category: 'material_palette', description: 'Material yellow' },

  // 17. Hex Aliases
  { color_key: 'hex_40000000', color_hex: '#00000040', color_value_hex_int: '0x40000000', category: 'hex_alias', description: 'Black 25% opacity' },
  { color_key: 'hex_FF009688', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'hex_alias', description: 'Teal brand mapping' },
  { color_key: 'hex_FF0F172A', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Slate dark mapping' },
  { color_key: 'hex_FF0F2027', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Gradient dark mapping' },
  { color_key: 'hex_FF1565C0', color_hex: '#16465D', color_value_hex_int: '0xFF16465D', category: 'hex_alias', description: 'Deep blue mapping' },
  { color_key: 'hex_FF1E1E2C', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Dark card mapping' },
  { color_key: 'hex_FF1E293B', color_hex: '#16465D', color_value_hex_int: '0xFF16465D', category: 'hex_alias', description: 'Slate 800 mapping' },
  { color_key: 'hex_FF203A43', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Dark gradient mid' },
  { color_key: 'hex_FF2196F3', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Material blue mapping' },
  { color_key: 'hex_FF263238', color_hex: '#16465D', color_value_hex_int: '0xFF16465D', category: 'hex_alias', description: 'Blue grey 900 mapping' },
  { color_key: 'hex_FF2C3E50', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Midnight blue mapping' },
  { color_key: 'hex_FF2C5364', color_hex: '#2C586A', color_value_hex_int: '0xFF2C586A', category: 'hex_alias', description: 'Gradient cyan dark' },
  { color_key: 'hex_FF2D0E15', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Deep wine dark mapping' },
  { color_key: 'hex_FF2D3436', color_hex: '#16465D', color_value_hex_int: '0xFF16465D', category: 'hex_alias', description: 'Charcoal dark mapping' },
  { color_key: 'hex_FF2E7D32', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'hex_alias', description: 'Green 800 mapping' },
  { color_key: 'hex_FF333333', color_hex: '#013952', color_value_hex_int: '0xFF013952', category: 'hex_alias', description: 'Off black mapping' },
  { color_key: 'hex_FF334155', color_hex: '#2C586A', color_value_hex_int: '0xFF2C586A', category: 'hex_alias', description: 'Slate 700 mapping' },
  { color_key: 'hex_FF475569', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'hex_alias', description: 'Slate 600 mapping' },
  { color_key: 'hex_FF4B68FF', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'hex_alias', description: 'Primary action blue' },
  { color_key: 'hex_FF50041B', color_hex: '#005047', color_value_hex_int: '0xFF005047', category: 'hex_alias', description: 'Deep maroon mapping' },
  { color_key: 'hex_FF636E72', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'hex_alias', description: 'American river grey' },
  { color_key: 'hex_FF64748B', color_hex: '#52707D', color_value_hex_int: '0xFF52707D', category: 'hex_alias', description: 'Slate 500 mapping' },
  { color_key: 'hex_FF744210', color_hex: '#006E64', color_value_hex_int: '0xFF006E64', category: 'hex_alias', description: 'Dark gold/amber mapping' },
  { color_key: 'hex_FF8A1035', color_hex: '#006E64', color_value_hex_int: '0xFF006E64', category: 'hex_alias', description: 'Berry dark mapping' },
  { color_key: 'hex_FF8E8E8E', color_hex: '#7896A1', color_value_hex_int: '0xFF7896A1', category: 'hex_alias', description: 'Grey mapping' },
  { color_key: 'hex_FF94A3B8', color_hex: '#A1BBC3', color_value_hex_int: '0xFFA1BBC3', category: 'hex_alias', description: 'Slate 400 mapping' },
  { color_key: 'hex_FF9E9E9E', color_hex: '#7896A1', color_value_hex_int: '0xFF7896A1', category: 'hex_alias', description: 'Material grey 500 mapping' },
  { color_key: 'hex_FFB7791F', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'hex_alias', description: 'Warm amber mapping' },
  { color_key: 'hex_FFC62828', color_hex: '#D32F2F', color_value_hex_int: '0xFFD32F2F', category: 'hex_alias', description: 'Red 800 mapping' },
  { color_key: 'hex_FFC71D52', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'hex_alias', description: 'Magenta mapping' },
  { color_key: 'hex_FFE0EAFC', color_hex: '#E4EFF1', color_value_hex_int: '0xFFE4EFF1', category: 'hex_alias', description: 'Soft gradient light' },
  { color_key: 'hex_FFE2E8F0', color_hex: '#E4EFF1', color_value_hex_int: '0xFFE4EFF1', category: 'hex_alias', description: 'Slate 200 mapping' },
  { color_key: 'hex_FFE3F2FD', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'hex_alias', description: 'Light blue 50 mapping' },
  { color_key: 'hex_FFE5F1FB', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'hex_alias', description: 'Soft sky tint mapping' },
  { color_key: 'hex_FFE8F5E1', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'hex_alias', description: 'Light green tint' },
  { color_key: 'hex_FFE8F5E9', color_hex: '#D7F7F2', color_value_hex_int: '0xFFD7F7F2', category: 'hex_alias', description: 'Green 50 mapping' },
  { color_key: 'hex_FFEAF2FF', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'hex_alias', description: 'Ice blue mapping' },
  { color_key: 'hex_FFEDE6E9', color_hex: '#E4EFF1', color_value_hex_int: '0xFFE4EFF1', category: 'hex_alias', description: 'Soft grey mapping' },
  { color_key: 'hex_FFEF6C00', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'hex_alias', description: 'Orange 800 mapping' },
  { color_key: 'hex_FFEFA100', color_hex: '#00AA9A', color_value_hex_int: '0xFF00AA9A', category: 'hex_alias', description: 'Golden orange mapping' },
  { color_key: 'hex_FFF0F0F0', color_hex: '#F0F7F7', color_value_hex_int: '0xFFF0F7F7', category: 'hex_alias', description: 'Light grey base' },
  { color_key: 'hex_FFF0F2F5', color_hex: '#F0F7F7', color_value_hex_int: '0xFFF0F7F7', category: 'hex_alias', description: 'Facebook grey background' },
  { color_key: 'hex_FFF1F3F5', color_hex: '#F0F7F7', color_value_hex_int: '0xFFF0F7F7', category: 'hex_alias', description: 'Grey 100 mapping' },
  { color_key: 'hex_FFF1F4F9', color_hex: '#F4FAFA', color_value_hex_int: '0xFFF4FAFA', category: 'hex_alias', description: 'Dashboard light surface' },
  { color_key: 'hex_FFF1F5F9', color_hex: '#F4FAFA', color_value_hex_int: '0xFFF4FAFA', category: 'hex_alias', description: 'Slate 100 mapping' },
  { color_key: 'hex_FFF499B1', color_hex: '#A9EFE6', color_value_hex_int: '0xFFA9EFE6', category: 'hex_alias', description: 'Soft highlight tint' },
  { color_key: 'hex_FFF4F6F9', color_hex: '#F4FAFA', color_value_hex_int: '0xFFF4FAFA', category: 'hex_alias', description: 'Admin background tint' },
  { color_key: 'hex_FFF5F5F5', color_hex: '#F0F7F7', color_value_hex_int: '0xFFF0F7F7', category: 'hex_alias', description: 'Grey 50 surface' },
  { color_key: 'hex_FFF5F7FA', color_hex: '#F4FAFA', color_value_hex_int: '0xFFF4FAFA', category: 'hex_alias', description: 'Cloud grey surface' },
  { color_key: 'hex_FFF6F7FB', color_hex: '#F6FBFB', color_value_hex_int: '0xFFF6FBFB', category: 'hex_alias', description: 'Light surface base' },
  { color_key: 'hex_FFF7F8FC', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'hex_alias', description: 'Pure surface tint' },
  { color_key: 'hex_FFF7F9FC', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'hex_alias', description: 'Surface light' },
  { color_key: 'hex_FFF8F5F6', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'hex_alias', description: 'Light pinkish surface' },
  { color_key: 'hex_FFF8F6F7', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'hex_alias', description: 'Soft white surface' },
  { color_key: 'hex_FFF8FAFC', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'hex_alias', description: 'Slate 50 surface' },
  { color_key: 'hex_FFF9A825', color_hex: '#00AA9A', color_value_hex_int: '0xFF00AA9A', category: 'hex_alias', description: 'Yellow 800 mapping' },
  { color_key: 'hex_FFFAF8F9', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'hex_alias', description: 'Subtle warm surface' },
  { color_key: 'hex_FFFAFAFA', color_hex: '#F8FCFC', color_value_hex_int: '0xFFF8FCFC', category: 'hex_alias', description: 'Material grey 50 base' },
  { color_key: 'hex_FFFBC02D', color_hex: '#00C8B6', color_value_hex_int: '0xFF00C8B6', category: 'hex_alias', description: 'Yellow 700 mapping' },
  { color_key: 'hex_FFFF6D00', color_hex: '#008B7E', color_value_hex_int: '0xFF008B7E', category: 'hex_alias', description: 'Orange accent mapping' },
  { color_key: 'hex_FFFFE2E2', color_hex: '#FFEBEE', color_value_hex_int: '0xFFFFEBEE', category: 'hex_alias', description: 'Red highlight tint' },
  { color_key: 'hex_FFFFE9DA', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'hex_alias', description: 'Warm highlight tint' },
  { color_key: 'hex_FFFFEBEE', color_hex: '#FFEBEE', color_value_hex_int: '0xFFFFEBEE', category: 'hex_alias', description: 'Red 50 badge' },
  { color_key: 'hex_FFFFF3E0', color_hex: '#FFF3E0', color_value_hex_int: '0xFFFFF3E0', category: 'hex_alias', description: 'Orange 50 badge' },
  { color_key: 'hex_FFFFF5D6', color_hex: '#F0FCFA', color_value_hex_int: '0xFFF0FCFA', category: 'hex_alias', description: 'Yellow 50 tint' }
];

module.exports = defaultFieldOmniColors;
